name: Deploy to Koyeb

on:
  push:
    branches:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: "${{ github.ref_name }}"
      cancel-in-progress: true
    steps:
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_API_TOKEN }}"

      - name: Build and deploy the application to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: test-deploy-flask
          service-name: my-koyeb-service
          service-env: FOO=barxxx,BAZ=quxxxx
          service-ports: "8000:http"
          service-routes: "/:8000"
          service-checks: "8000:http:/"
